import {
	menu_img_1,
	menu_img_2,
	menu_img_3,
	menu_img_4,
	menu_img_5,
	menu_img_6,
	menu_img_7,
	menu_img_8,
	menu_img_9,
	menu_img_10,
	menu_img_11,
	menu_img_12,
} from "./home_images";

const items = [
	{
		id: 1,
		title: "caffe latte",
		category: "latte",
		price: 2.95,
		desc: "Fresh brewed coffee and steamed milk",
		img: menu_img_1,
	},
	{
		id: 2,
		title: "caffe mocha",
		category: "mocha",
		price: 3.67,
		desc: "Espresso With Milk, and Whipped Cream",
		img: menu_img_2,
	},
	{
		id: 3,
		title: "white chocolate mocha",
		price: 2.79,
		category: "mocha",
		desc: "Espresso, White Chocolate, Milk, Ice and Cream",
		img: menu_img_3,
	},
	{
		id: 4,
		title: "caffe americano",
		category: "americano",
		price: 3.06,
		desc: "Espresso Shots and Light Layer of Crema",
		img: menu_img_4,
	},
	{
		id: 5,
		title: "cappuccino",
		category: "cappuccino",
		price: 4.03,
		desc: "Espresso, and Smoothed Layer of Foam",
		img: menu_img_5,
	},
	{
		id: 6,
		title: "vanilla latte",
		category: "latte",
		price: 3.65,
		desc: "Espresso Milk With Flavor, and Cream",
		img: menu_img_6,
	},
	{
		id: 7,
		title: "iced caramel latte",
		category: "latte",
		price: 4.67,
		desc: "Espresso, Milk, Ice and Caramel Sauce",
		img: menu_img_7,
	},
	{
		id: 8,
		title: "espresso macchiato",
		category: "macchiato",
		price: 2.98,
		desc: "Rich Espresso With Milk and Foam",
		img: menu_img_8,
	},
	{
		id: 9,
		title: "caramel macchiato",
		category: "macchiato",
		price: 2.54,
		desc: "Espresso, vanilla-flavored syrup and milk",
		img: menu_img_9,
	},
	{
		id: 10,
		title: "iced smoked latte",
		category: "latte",
		price: 3.05,
		desc: "Espresso, ice, with smoked butterscotch",
		img: menu_img_10,
	},
	{
		id: 11,
		title: "iced caffe mocha",
		category: "mocha",
		price: 2.61,
		desc: "Espresso, bittersweet mocha sauce, milk and ice",
		img: menu_img_11,
	},
	{
		id: 12,
		title: "iced gingerbread latte",
		category: "latte",
		price: 3.92,
		desc: "Espresso, Milk, Ice, and Gingerbread Flavor",
		img: menu_img_12,
	},
];

export default items;
